---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: every-deployment
  labels:
    app: every
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.every: "glob:staging-*"
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: every
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9797"
      labels:
        app: every
    spec:
      serviceAccountName: default
      containers:
      - name: every
        image: vase/every-dashboard:staging-335177d
        resources:
          requests:
            cpu: 250m
            memory: "750Mi"
          limits:
            cpu: 500m
            memory: "1.5G"
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: every
      imagePullSecrets:
      - name: regcred
