apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: every-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - every.worker.osama.vaseinfra.net
    - port:
        number: 443
        name: https-every
        protocol: HTTPS
      hosts:
        - "every.worker.osama.vaseinfra.net"
      tls:
        mode: SIMPLE
        credentialName: "every-secret"
