---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: every-deployment
  labels:
    app: every
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: every
  template:
    metadata:
      labels:
        app: every
    spec:
      serviceAccountName: default
      containers:
      - name: every
        image: vase/every-dashboard:d1f2353
        resources:
          requests:
            cpu: 250m
            memory: "750Mi"
          limits:
            cpu: 500m
            memory: "1.5G"
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: every
      imagePullSecrets:
      - name: regcred
