---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
  namespace: demo
  labels:
    app: helloworld
  annotations:
    fluxcd.io/automated: "true"
    # fluxcd.io/tag.init: regex:^3.10.*
    # fluxcd.io/tag.podinfod: semver:~3.1
spec:
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: istio/examples-helloworld-v1
          resources:
            requests:
              cpu: "100m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
