apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: demo
  labels:
    app: helloworld
spec:
  type: ClusterIP
  ports:
    - port: 5000
      name: http
  selector:
    app: helloworld
